server {
    listen 80;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/voice/ {
        proxy_pass http://voice:8001/voice/;
        proxy_set_header Host $host;
    }

    location /api/ {
        proxy_pass http://agent:8000/;
        proxy_set_header Host $host;
    }

    location /bill-api/ {
        proxy_pass http://bills:8002/;
        proxy_set_header Host $host;
    }
}
